# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install-poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -


      - name: Configure creds
        env: # Or as an environment variable
          PYPI_USER: ${{ secrets.PYPI_USER }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: source $HOME/.poetry/env && poetry config http-basic.pypi $PYPI_USER $PYPI_PASSWORD

      # Runs a single command using the runners shell
      - name: Release new version of package
        run: source $HOME/.poetry/env && make release

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actor
          message: '[skip ci]'
          push: true
          add: '.'
